config/routes.rb
Rails.application.routes.draw do
  get 'answers/show'
  get 'answers/create'
  resources :polls do
    resources :options
    resource :answer, only: %i[show create]
  end

  post 'search' => 'visualization#show'

  resources :welcome, only: %i[index]

  root 'welcome#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :poll
  belongs_to :option
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :poll
  has_many :answers
  # TODO: Add Uniqueness validation scope to parent Poll
  validates :title, presence: true
end

app/models/poll.rb
class Poll < ApplicationRecord
  extend FriendlyId
  friendly_id :slug_candidates, use: %i[slugged finders]

  has_many :options, dependent: :destroy
  has_many :answers
  validates :title, presence: true
  accepts_nested_attributes_for :options, allow_destroy: true, update_only: true
  accepts_nested_attributes_for :answers, allow_destroy: true

  private

  def hex
    SecureRandom.hex(3)
  end

  def slug_candidates
    [
      hex,
      [hex, hex],
      [hex, hex, hex]
    ]
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def show; end

  def create; end

  private

  def answers_params
    params.permit(answers_attributes: %i[poll_id option_id user_id _destroy])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include UserSessionsHelper
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  private

  def record_not_found
    redirect_to root_path
  end

  def logged_in_user
    unless been_here_before?
      store_location
      flash[:danger] = 'Please add a name.'
      redirect_to root_url
    end
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, except: %i[new index create]

  def new
    @poll = Poll.new
  end

  def edit
    @poll.options.build
  end

  def create
    @poll = Poll.create(poll_params)

    respond_to do |format|
      if @poll.save
        format.html { redirect_to edit_poll_path(@poll), notice: 'Poll created' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    if @poll.update(poll_params)
      if poll_params.has_key?(:answers_attributes)
        render 'visualization/show', notice: 'Poll was successfully updated.'
      else
        redirect_to edit_poll_path(@poll), notice: 'Poll was successfully updated.'
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def show; end

  private

  def set_poll
    @poll = Poll.find(params[:id])
  end

  def poll_params
    params.require(:poll).permit(:id, :title,
                                 options_attributes: %i[id poll_id title _destroy],
                                 answers_attributes: %i[poll_id user_id option_id _destroy])
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(name: params[:session][:name].downcase)
    if user
      set_user user
    else
      name = params[:session][:name]
      create_user name
      set_user
    end
  end

  def destroy
    remove_user
    redirect_to root_url
  end
end

app/controllers/visualization_controller.rb
# frozen_string_literal: true

class VisualizationController < ApplicationController
  before_action :add_user, only: [:show]

  def show
    # NOTE: Increase clarity in params
    @poll = Poll.find(params[:poll][:id])

    respond_to do |format|
      if @poll
        format.html { render 'respond' }
      else
        format.html { redirect_to :root, status: 404 }
      end
    end
  end

  private

  def add_user
    session[:name] = params[:poll][:name] if session[:name].nil?
    set_user(session[:name])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
  def set_user(name)
    if session[:user_id].nil?
      user = create_user(name)
      session[:user_id] = user.id
    end
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def been_here_before?
    !current_user.nil?
  end

  def create_user(name)
    User.create(name: name)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/visualization_helper.rb
module VisualizationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/answers/create.html.haml
%h1 Answers#create
%p Find me in app/views/answers/create.html.haml

app/views/answers/show.html.haml
%h1 Answers#show
%p Find me in app/views/answers/show.html.haml

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title PollAnywhereRedux

    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"

  %body.min-h-screen
    .navbar.bg-base-100
      .navbar-start
        %a.btn.btn-ghost{:href => "/"}
          = image_tag "icon", class: "img", class: "mr-3 h-14 sm:h-9"
      .navbar-center.text-center
        %a.btn.btn-ghost.normal-case.text-xl{:href => "/"} Poll Anywhere Redux
      .navbar-end
    = yield

app/views/options/_new.html.haml
= simple_form_for [poll, poll.options.build ] do |f|
  = f.input :title
  = f.associaton :poll

app/views/polls/_form.html.haml
= simple_form_for :poll do |f|
    = f.input :title, label: "Poll Title"
    = render partial: 'polls/options', collection: poll.options, as: :option
    = f.simple_fields_for :options do |option_form|
        = option_form.input :title, placeholder: "Type new option"
        = option_form.hidden_field :id, value: poll.id
    = f.button :submit, "Submit"

app/views/polls/edit.html.haml
%section.max-h-screen
  .hero.bg-base-200.pb-40
    .hero-content.flex-col
      %ul.steps.steps.vertical.py-4
        %li.step.step-primary Create Poll
        %li.step.step-primary Add Answers
        %li.step Send it out
      .text-center.lg:text-left
        %p.text-lg Fine-tune Your Poll
      .card.min-w-screen.shadow-2xl.bg-base-100
        .card-body
          .form-control.grid.grid-rows-1
            = simple_form_for @poll do |f|
              = f.hidden_field :id, value: @poll.id
              %label.label Poll Title
              .text-center.lg:text-left
                = f.input_field :title, placeholder: "Poll Title", class: "text-2xl base-200 bg-base-100 hover:bg-base-200"
              -# = render partial: 'polls/options', collection: @poll.options, as: :option
              .grid.grid-rows-1.py-2
                %p Options
                = f.simple_fields_for :options do |option_form|
                  = option_form.hidden_field :poll_id, value: @poll.id
                  .py-2.shadow-md
                    %label.input-group
                      = option_form.input_field :title, placeholder: "Type new option", class: "input input-bordered w-full hover:input-primary"
                      %label.swap
                        = option_form.check_box :_destroy, class: "bg-base-200"
                        %span.swap-off.label-text.py-3.bg-primary.rounded-md
                          %svg{:fill => "none", :height => "24", :stroke => "#000000", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "2", :viewbox => "0 0 24 24", :width => "24", :xmlns => "http://www.w3.org/2000/svg"}>
                            %polyline{:points => "20 6 9 17 4 12"}
                        %span.swap-on.label-text.bg-secondary
                          %svg{:fill => "none", :height => "24", :stroke => "#000000", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "2", :viewbox => "0 0 24 24", :width => "24", :xmlns => "http://www.w3.org/2000/svg"}
                            %polyline{:points => "3 6 5 6 21 6"}
                            %path{:d => "M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"}
                            %line{:x1 => "10", :x2 => "10", :y1 => "11", :y2 => "17"}
                            %line{:x1 => "14", :x2 => "14", :y1 => "11", :y2 => "17"}                        %span.swap-off.label-text
              .btn-group
                = f.button :submit, "Submit", class: "btn bg-base-200"
                %button.btn.bg-base-200.swap.swap-rotate.flex{:onclick => "this.classList.add('swap-active'); navigator.clipboard.writeText('#{@poll.friendly_id}'); this.firstChild.textContent = 'Copied ID'", :type => "button"}
                  Tap to Poll ID
                  %svg.swap-off{"aria-hidden" => "true", :height => "1em", :preserveaspectratio => "xMidYMid meet", :role => "img", :viewbox => "0 0 384 512", :width => "0.75em", :xmlns => "http://www.w3.org/2000/svg"}
                    %path{:d => "M384 112v352c0 26.51-21.49 48-48 48H48c-26.51 0-48-21.49-48-48V112c0-26.51 21.49-48 48-48h80c0-35.29 28.71-64 64-64s64 28.71 64 64h80c26.51 0 48 21.49 48 48zM192 40c-13.255 0-24 10.745-24 24s10.745 24 24 24s24-10.745 24-24s-10.745-24-24-24m96 114v-20a6 6 0 0 0-6-6H102a6 6 0 0 0-6 6v20a6 6 0 0 0 6 6h180a6 6 0 0 0 6-6z", :fill => "currentColor"}
                  %svg.swap-on{"aria-hidden" => "true", :height => "1em", :preserveaspectratio => "xMidYMid meet", :role => "img", :viewbox => "0 0 384 512", :width => "0.75em", :xmlns => "http://www.w3.org/2000/svg"}
                    %path{:d => "M336 64h-80c0-35.3-28.7-64-64-64s-64 28.7-64 64H48C21.5 64 0 85.5 0 112v352c0 26.5 21.5 48 48 48h288c26.5 0 48-21.5 48-48V112c0-26.5-21.5-48-48-48zM192 40c13.3 0 24 10.7 24 24s-10.7 24-24 24s-24-10.7-24-24s10.7-24 24-24zm121.2 231.8l-143 141.8c-4.7 4.7-12.3 4.6-17-.1l-82.6-83.3c-4.7-4.7-4.6-12.3.1-17L99.1 285c4.7-4.7 12.3-4.6 17 .1l46 46.4l106-105.2c4.7-4.7 12.3-4.6 17 .1l28.2 28.4c4.7 4.8 4.6 12.3-.1 17z", :fill => "currentColor"}

app/views/polls/new.html.haml
%section.max-h-screen
  .hero.bg-base-200.pb-40
    .hero-content.flex-col
      %ul.steps.steps.vertical.py-4
        %li.step.step-primary Create Poll
        %li.step Add Answers
        %li.step Send it out
      .text-center.lg:text-left
        %p.text-lg Name Your Poll
      .card.min-w-screen.shadow-2xl.bg-base-100
        .card-body
          .form-control.grid.grid-rows-1
            = simple_form_for @poll do |f|
              = f.hidden_field :id, value: @poll.id
              %label.label Poll Title
              .text-center.lg:text-left
                = f.input_field :title, placeholder: "Poll Title", class: "input text-2xl  bg-base-100 hover:bg-base-200"
              -# = render partial: 'polls/options', collection: @poll.options, as: :option
              = f.button :submit, "Submit", class: "btn bg-base-200"

app/views/visualization/respond.html.haml
%section.max-h-screen
  .hero.bg-base-200
    .hero-content.flex-col
      .text-center.text-4xl
        = @poll.title
      .form-control
        = simple_form_for @poll do |f|
          = f.hidden_field :id, value: @poll.id
          .grid.grid-cols-2.gap-6
            = f.simple_fields_for :options do |option|
              %label.input-group.rounded-md
                .stats.swap{id: "checkbox-#{option.object.id}"}
                  - title = option.object.title
                  = f.simple_fields_for :answers, @poll.answers.build do |answer|
                    = answer.hidden_field :poll_id, value: @poll.id
                    = answer.hidden_field :option_id, value: option.object.id
                    = answer.hidden_field :user_id, value: session[:user_id], id: "user-#{option.object.id}"
                    = answer.check_box :_destroy, {}, '0', '1'
                  .swap-off.label-text.py-3.bg-base-100.w-60
                    .stat
                      .stat-title.text-xl
                        = title
                      .stat-value
                        = option.object.answers.count
                      .stat-desc
                      .stat-figure
                        %svg{:fill => "none", :height => "24", :stroke => "#000000", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "1", :viewbox => "0 0 24 24", :width => "34", :xmlns => "http://www.w3.org/2000/svg"}>
                          %path{:d => "M10.544,8.717l1.166-0.855l1.166,0.855l-0.467-1.399l1.012-0.778h-1.244L11.71,5.297l-0.466,1.244H10l1.011,0.778L10.544,8.717z M15.986,9.572l-0.467,1.244h-1.244l1.011,0.777l-0.467,1.4l1.167-0.855l1.165,0.855l-0.466-1.4l1.011-0.777h-1.244L15.986,9.572z M7.007,6.552c0-2.259,0.795-4.33,2.117-5.955C4.34,1.042,0.594,5.07,0.594,9.98c0,5.207,4.211,9.426,9.406,9.426c2.94,0,5.972-1.354,7.696-3.472c-0.289,0.026-0.987,0.044-1.283,0.044C11.219,15.979,7.007,11.759,7.007,6.552 M10,18.55c-4.715,0-8.551-3.845-8.551-8.57c0-3.783,2.407-6.999,5.842-8.131C6.549,3.295,6.152,4.911,6.152,6.552c0,5.368,4.125,9.788,9.365,10.245C13.972,17.893,11.973,18.55,10,18.55 M19.406,2.304h-1.71l-0.642-1.71l-0.642,1.71h-1.71l1.39,1.069l-0.642,1.924l1.604-1.176l1.604,1.176l-0.642-1.924L19.406,2.304z", :fill => "none"}
                  .swap-on.label-text.bg-primary.w-60
                    .stat
                      .stat-title.text-xl.text-white
                        = title
                      .stat-value
                        = option.object.answers.count + 1
                      .stat-desc.text-white
                        = "#{session[:name]} is voting"
                      .stat-figure
                        %svg{:fill => "none", :height => "24", :stroke => "#FFFFFF", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "1", :viewbox => "0 0 24 24", :width => "34", :xmlns => "http://www.w3.org/2000/svg"}>
                          %path{:d => "M5.114,5.726c0.169,0.168,0.442,0.168,0.611,0c0.168-0.169,0.168-0.442,0-0.61L3.893,3.282c-0.168-0.168-0.442-0.168-0.61,0c-0.169,0.169-0.169,0.442,0,0.611L5.114,5.726z M3.955,10c0-0.239-0.193-0.432-0.432-0.432H0.932C0.693,9.568,0.5,9.761,0.5,10s0.193,0.432,0.432,0.432h2.591C3.761,10.432,3.955,10.239,3.955,10 M10,3.955c0.238,0,0.432-0.193,0.432-0.432v-2.59C10.432,0.693,10.238,0.5,10,0.5S9.568,0.693,9.568,0.932v2.59C9.568,3.762,9.762,3.955,10,3.955 M14.886,5.726l1.832-1.833c0.169-0.168,0.169-0.442,0-0.611c-0.169-0.168-0.442-0.168-0.61,0l-1.833,1.833c-0.169,0.168-0.169,0.441,0,0.61C14.443,5.894,14.717,5.894,14.886,5.726 M5.114,14.274l-1.832,1.833c-0.169,0.168-0.169,0.441,0,0.61c0.168,0.169,0.442,0.169,0.61,0l1.833-1.832c0.168-0.169,0.168-0.442,0-0.611C5.557,14.106,5.283,14.106,5.114,14.274 M19.068,9.568h-2.591c-0.238,0-0.433,0.193-0.433,0.432s0.194,0.432,0.433,0.432h2.591c0.238,0,0.432-0.193,0.432-0.432S19.307,9.568,19.068,9.568 M14.886,14.274c-0.169-0.168-0.442-0.168-0.611,0c-0.169,0.169-0.169,0.442,0,0.611l1.833,1.832c0.168,0.169,0.441,0.169,0.61,0s0.169-0.442,0-0.61L14.886,14.274z M10,4.818c-2.861,0-5.182,2.32-5.182,5.182c0,2.862,2.321,5.182,5.182,5.182s5.182-2.319,5.182-5.182C15.182,7.139,12.861,4.818,10,4.818M10,14.318c-2.385,0-4.318-1.934-4.318-4.318c0-2.385,1.933-4.318,4.318-4.318c2.386,0,4.318,1.933,4.318,4.318C14.318,12.385,12.386,14.318,10,14.318 M10,16.045c-0.238,0-0.432,0.193-0.432,0.433v2.591c0,0.238,0.194,0.432,0.432,0.432s0.432-0.193,0.432-0.432v-2.591C10.432,16.238,10.238,16.045,10,16.045", :fill => "none"}
          = f.button :submit, "Submit", class: "btn bg-base-200"

app/views/visualization/show.html.haml
%section.max-h-screen
  .hero.bg-base-200
    .hero-content.flex-col
      .text-center.text-4xl
        = @poll.title
      .form-control
        = simple_form_for @poll do |f|
          .grid.grid-cols-2.gap-6
            - @poll.options.each do |option|
              %label.input-group.rounded-md
                .stats.swap{id: "option-#{option.id}"}
                  - title = option.title
                  .swap-off.label-text.py-3.bg-base-100.w-60
                    .stat
                      .stat-title.text-xl
                        = title
                      .stat-value
                        = option.answers.count
                      .stat-desc
                      .stat-figure
                        %svg{:fill => "none", :height => "24", :stroke => "#000000", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "1", :viewbox => "0 0 24 24", :width => "34", :xmlns => "http://www.w3.org/2000/svg"}>
                          %path{:d => "M10.544,8.717l1.166-0.855l1.166,0.855l-0.467-1.399l1.012-0.778h-1.244L11.71,5.297l-0.466,1.244H10l1.011,0.778L10.544,8.717z M15.986,9.572l-0.467,1.244h-1.244l1.011,0.777l-0.467,1.4l1.167-0.855l1.165,0.855l-0.466-1.4l1.011-0.777h-1.244L15.986,9.572z M7.007,6.552c0-2.259,0.795-4.33,2.117-5.955C4.34,1.042,0.594,5.07,0.594,9.98c0,5.207,4.211,9.426,9.406,9.426c2.94,0,5.972-1.354,7.696-3.472c-0.289,0.026-0.987,0.044-1.283,0.044C11.219,15.979,7.007,11.759,7.007,6.552 M10,18.55c-4.715,0-8.551-3.845-8.551-8.57c0-3.783,2.407-6.999,5.842-8.131C6.549,3.295,6.152,4.911,6.152,6.552c0,5.368,4.125,9.788,9.365,10.245C13.972,17.893,11.973,18.55,10,18.55 M19.406,2.304h-1.71l-0.642-1.71l-0.642,1.71h-1.71l1.39,1.069l-0.642,1.924l1.604-1.176l1.604,1.176l-0.642-1.924L19.406,2.304z", :fill => "none"}
                  .swap-on.label-text.bg-primary.w-60
                    .stat
                      .stat-title.text-xl.text-white
                        = title
                      .stat-value
                        = option.answers.count + 1
                      .stat-desc.text-white
                        = "#{session[:name]} is voting"
                      .stat-figure
                        %svg{:fill => "none", :height => "24", :stroke => "#FFFFFF", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "1", :viewbox => "0 0 24 24", :width => "34", :xmlns => "http://www.w3.org/2000/svg"}>
                          %path{:d => "M5.114,5.726c0.169,0.168,0.442,0.168,0.611,0c0.168-0.169,0.168-0.442,0-0.61L3.893,3.282c-0.168-0.168-0.442-0.168-0.61,0c-0.169,0.169-0.169,0.442,0,0.611L5.114,5.726z M3.955,10c0-0.239-0.193-0.432-0.432-0.432H0.932C0.693,9.568,0.5,9.761,0.5,10s0.193,0.432,0.432,0.432h2.591C3.761,10.432,3.955,10.239,3.955,10 M10,3.955c0.238,0,0.432-0.193,0.432-0.432v-2.59C10.432,0.693,10.238,0.5,10,0.5S9.568,0.693,9.568,0.932v2.59C9.568,3.762,9.762,3.955,10,3.955 M14.886,5.726l1.832-1.833c0.169-0.168,0.169-0.442,0-0.611c-0.169-0.168-0.442-0.168-0.61,0l-1.833,1.833c-0.169,0.168-0.169,0.441,0,0.61C14.443,5.894,14.717,5.894,14.886,5.726 M5.114,14.274l-1.832,1.833c-0.169,0.168-0.169,0.441,0,0.61c0.168,0.169,0.442,0.169,0.61,0l1.833-1.832c0.168-0.169,0.168-0.442,0-0.611C5.557,14.106,5.283,14.106,5.114,14.274 M19.068,9.568h-2.591c-0.238,0-0.433,0.193-0.433,0.432s0.194,0.432,0.433,0.432h2.591c0.238,0,0.432-0.193,0.432-0.432S19.307,9.568,19.068,9.568 M14.886,14.274c-0.169-0.168-0.442-0.168-0.611,0c-0.169,0.169-0.169,0.442,0,0.611l1.833,1.832c0.168,0.169,0.441,0.169,0.61,0s0.169-0.442,0-0.61L14.886,14.274z M10,4.818c-2.861,0-5.182,2.32-5.182,5.182c0,2.862,2.321,5.182,5.182,5.182s5.182-2.319,5.182-5.182C15.182,7.139,12.861,4.818,10,4.818M10,14.318c-2.385,0-4.318-1.934-4.318-4.318c0-2.385,1.933-4.318,4.318-4.318c2.386,0,4.318,1.933,4.318,4.318C14.318,12.385,12.386,14.318,10,14.318 M10,16.045c-0.238,0-0.432,0.193-0.432,0.433v2.591c0,0.238,0.194,0.432,0.432,0.432s0.432-0.193,0.432-0.432v-2.591C10.432,16.238,10.238,16.045,10,16.045", :fill => "none"}

app/views/welcome/index.html.haml
%section.px-4.py-24.mx-auto.max-w-7xl.hero.min-h-screen
  .w-full.mx-auto.text-left.md:text-center{:class => "md:w-11/12 xl:w-9/12"}
    %h1.mb-6.text-4xl.font-extrabold.leading-none.tracking-normal.text-base-900.md:text-6xl.md:tracking-tight
      Share your
      %span.block.w-full.text-transparent.bg-clip-text.bg-gradient-to-r.from-green-400.to-purple-500.lg:inline thoughts and opinons
    %p.px-0.mb-6.text-lg.md:text-xl.lg:px-24
      Multiple Choice Questions Running on Full Stack Technology from the 22nd Century.
    .mb-4.space-x-0.md:space-x-2.md:mb-8
    .grid.grid-cols-2.py-6.shadow-2xl
      .container
        .card.min-h-full.text-center.lg:text-left.min-w-full
          .card-body
            %h1.text-2xl.font-bold
              For
              %span.block.w-full.text-transparent.bg-clip-text.bg-gradient-to-r.from-green-400.to-purple-500.inline Audience Members
            %p.text-lg Type the shared ID here and join the live poll!
            .form-control
              = simple_form_for :poll, url: :search do |f|
                %label.label Join by ID
                = f.input_field :id, class: "input input-bordered w-full max-w-xs", placeholder: "Join by ID"
                %label.label Add your name
                = f.input_field :name, class: "input input-bordered w-full max-w-xs", placeholder: "Name"
                = f.submit "Join", class: "btn"
      .container
        .card.min-h-full.text-center.lg:text-left
          .card-body
            %h1.text-2xl.font-bold For Hosts
            %p.py-6.text-lg Make a Kahoot for you and your friends!
            %button.btn
              = link_to "New Poll", new_poll_path